from typing import Any

import ollama
import requests
from google import genai

from config.api_keys import GEMINI_API_KEY, MISTRAL_API_KEY
from core.logger import get_logger

logger = get_logger(__name__)

MISTRAL_MODEL = "mistral-small-2506"
MISTRAL_URL = "https://api.mistral.ai/v1/chat/completions"
MISTRAL_TIMEOUT_SECONDS = 30


class _UsageMetadata:
    """Mimics the shape of google-genai's `usage_metadata`, so callers can
    read token counts the same way regardless of which provider answered."""

    def __init__(
        self, prompt_token_count: int, candidates_token_count: int, total_token_count: int
    ):
        self.prompt_token_count = prompt_token_count
        self.candidates_token_count = candidates_token_count
        self.total_token_count = total_token_count


class _LLMResponse:
    """Mimics the shape of google-genai's response (`.text`, `.usage_metadata`)
    so `getResponseFromLLM` returns a consistent object whether Gemini or
    Mistral actually produced the answer."""

    def __init__(self, text: str | None, usage_metadata: _UsageMetadata | None = None):
        self.text = text
        self.usage_metadata = usage_metadata


def _call_gemini(system_prompt: str, user_prompt: str, model_temp: float, format: str):
    """Calls Gemini and returns its raw response, or None if the call
    raised or came back without any text."""
    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
        response_format = "application/json" if format == "json" else "text/plain"

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=user_prompt,
            config=genai.types.GenerateContentConfig(
                system_instruction=system_prompt,
                response_mime_type=response_format,
                temperature=model_temp,
            ),
        )

        if response is not None and response.text:
            logger.info("Gemini responded successfully (%d chars)", len(response.text))
            return response

        logger.warning("Gemini returned an empty response")
        return None
    except Exception as e:
        logger.error("Gemini call failed: %s", e)
        return None


def _call_mistral(system_prompt: str, user_prompt: str, model_temp: float, format: str):
    """Calls Mistral's chat completions endpoint as a fallback for when
    Gemini is unavailable or out of tokens. Wraps the response so it looks
    like a Gemini response to the rest of the codebase."""
    logger.info("Falling back to Mistral (%s)", MISTRAL_MODEL)

    payload: dict[str, Any] = {
        "model": MISTRAL_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": model_temp,
    }
    if format == "json":
        payload["response_format"] = {"type": "json_object"}

    try:
        response = requests.post(
            MISTRAL_URL,
            headers={
                "Authorization": f"Bearer {MISTRAL_API_KEY}",
                "Content-Type": "application/json",
            },
            json=payload,
            timeout=MISTRAL_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        data = response.json()

        text = data["choices"][0]["message"]["content"]
        usage = data.get("usage", {})
        usage_metadata = _UsageMetadata(
            prompt_token_count=usage.get("prompt_tokens", 0) or 0,
            candidates_token_count=usage.get("completion_tokens", 0) or 0,
            total_token_count=usage.get("total_tokens", 0) or 0,
        )

        logger.info("Mistral responded successfully (%d chars)", len(text or ""))
        return _LLMResponse(text=text, usage_metadata=usage_metadata)
    except Exception as e:
        logger.error("Mistral call failed: %s", e)
        return _LLMResponse(text=None)


def getResponseFromLLM(
    system_prompt: str, user_prompt: str, model_temp: float, format: str = "json"
):
    """Returns a response generated by an LLM for a given query with some
    given configs (temp, format...).

    Tries Gemini first. If Gemini raises or comes back empty (for example
    because its quota/tokens ran out), the exact same request is retried
    against Mistral, so callers always get a response object with `.text`
    and `.usage_metadata`, regardless of which provider answered.
    """
    gemini_response = _call_gemini(system_prompt, user_prompt, model_temp, format)
    if gemini_response is not None:
        return gemini_response

    return _call_mistral(system_prompt, user_prompt, model_temp, format)


def warm_up_embedding_model():
    ollama.embed(model="embeddinggemma", input="warmup")
